name: davgo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.0.3
  network_info_plus: ^6.0.0
  permission_handler: ^11.3.1
  fluttertoast: ^8.2.8
  path_provider: ^2.1.3
  shelf: ^1.4.1
  ftp_server: ^2.1.1
  file_picker: ^8.0.0
  path: ^1.9.0
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo2.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/wifi_black.png
    - assets/images/wifi_white.png
    - assets/images/webdav.png
    - assets/images/ftp.png

  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/roboto-condensed.ttf
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/roboto-mono.ttf
